# Generated by Django 2.2.6 on 2019-10-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chartreviewtool_dast_demographicmodel_hrrs_discharge_planning_hrrs_intake_screen_hrrs_progress_note_'),
    ]

    operations = [
        migrations.CreateModel(
            name='case_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_note', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Grievance_Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievance', models.CharField(max_length=100)),
                ('recognizes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rights_of_Each_Client_or_Bill_of_Rights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(max_length=100)),
                ('procedure', models.CharField(max_length=100)),
            ],
        ),
    ]
