# Generated by Django 2.2.6 on 2019-10-27 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_program_rules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case_note',
            options={'verbose_name_plural': 'Case Note'},
        ),
        migrations.AlterModelOptions(
            name='grievance_procedure',
            options={'verbose_name_plural': 'Grievance Procedure'},
        ),
        migrations.AlterModelOptions(
            name='program_rules',
            options={'verbose_name_plural': 'Program Rules'},
        ),
        migrations.AlterModelOptions(
            name='rights_of_each_client_or_bill_of_rights',
            options={'verbose_name_plural': 'Rights of Each Client/Bill of Rights'},
        ),
    ]
