# Generated by Django 2.2.6 on 2019-10-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='Option_1',
            field=models.CharField(choices=[('Alcohol use disorder', 'Alcohol use disorder'), ('Cannabis use disorder', 'Cannabis use disorder'), ('Cocaine use disorder', 'Cocaine use disorder'), ('Opioid use disorder', 'Opioid use disorder'), ('other hellucinogen use disorder', 'other hellucinogen use disorder'), ('Phencyclidine use disorder', 'Phencyclidine use disorder'), ('Sedative,hypnotic or anxiolytic use disorder', 'Sedative,hypnotic or anxiolytic use disorder')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='Option_2',
            field=models.CharField(choices=[('305.00', '305.00'), ('303.90', '303.90'), ('291.81', '291.81'), ('305.20', '305.20'), ('304.30', '304.30'), ('292.0', '292.0'), ('292.89', '292.89'), ('305.60', '305.60'), ('304.20', '304.20'), ('305.50', '305.50'), ('304.00', '304.00'), ('305.30', '305.30'), ('304.60', '304.60'), ('305.40', '305.40'), ('304.10', '304.10')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='Option_3',
            field=models.CharField(choices=[('F10.10', 'F10.10'), ('F10.20', 'F10.20'), ('F12.10', 'F12.10'), ('F12.288', 'F12.288'), ('F14.10', 'F14.10'), ('F14.20', 'F14.20'), ('F14.23', 'F14.23'), ('F11.10', 'F11.10'), ('F11.20', 'F11.20'), ('F11.23', 'F11.23'), ('F16.10', 'F16.10'), ('F116.20', 'F116.20'), ('F13.10', 'F13.10'), ('F13.20', 'F13.20')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='Option_4',
            field=models.CharField(choices=[('Alcohol use disorder,Mild', 'Alcohol use disorder,Mild'), ('Alcohol use disorder,Moderate', 'Alcohol use disorder,Moderate'), ('Alcohol use disorder,Severe', 'Alcohol use disorder,Severe'), ('Alcohol withdrawl', 'Alcohol withdrawl'), ('Cannabis use disorder,Mild', 'Cannabis use disorder,Mild'), ('Cannabis use disorder,Moderate', 'Cannabis use disorder,Moderate'), ('Cannabis use disorder,Severe', 'Cannabis use disorder,Severe'), ('Cannabis withdrawl', 'Cannabis withdrawl'), ('Cannabis-induced anxietu disorder', 'Cannabis-induced anxiety disorder'), ('Cocaine use disorder,Mild', 'Cocaine use disorder,Mild'), ('Cocaine use disorder,Moderate', 'Cocaine use disorder,Moderate'), ('Cocaine use disorder,Severe', 'Cocaine use disorder,Severe'), ('Cocaine withdrawl', 'Cocaine withdrawl'), ('Cocaine-induced anxiety disorder', 'Cocaine-induced anxiety disorder'), ('Opioid use disorder,Mild', 'Opioid use disorder,Mild'), ('Opioid use disorder,Moderate', 'Opioid use disorder,Moderate'), ('Opioid use disorder,Severe', 'Opioid use disorder,Severe'), ('Opioid withdrawl', 'Opioid withdrawl'), ('Opioid withdrawl,delirium', 'Opioid withdrawl,delirium'), ('other hellucinogen use disorder,Mild', 'other hellucinogen use disorder,Mild'), ('other hellucinogen use disorder,Moderate', 'other hellucinogen use disorder,Moderate'), ('other hellucinogen use disorder,Severe', 'other hellucinogen use disorder,Severe'), ('other hellucinogen-induced anxiety disorder', 'other hellucinogen-induced anxiety disorder'), ('Phencyclidine use disorder,Mild', 'Phencyclidine use disorder,Mild'), ('Phencyclidine use disorder,Moderate', 'Phencyclidine use disorder,Moderate'), ('Phencyclidine use disorder,Severe', 'Phencyclidine use disorder,Severe'), ('Phencyclidine-induced anxiety disorder', 'Phencyclidine-induced anxiety disorder'), ('Sedative,hypnotic or anxiolytic use disorder,Mild', 'Sedative,hypnotic or anxiolytic use disorder,Mild'), ('Sedative,hypnotic or anxiolytic use disorder,Mpderate', 'Sedative,hypnotic or anxiolytic use disorder,Moderate'), ('Sedative,hypnotic or anxiolytic use disorder,Severe', 'Sedative,hypnotic or anxiolytic use disorder,Severe'), ('Sedative,hypnotic or anxiolytic withdrawl', 'Sedative,hypnotic or anxiolytic withdrawl')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='referral_to',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('OP', 'OP'), ('IOP', 'IOP'), ('other', 'other')], max_length=100),
        ),
    ]
