# Generated by Django 2.2.6 on 2019-10-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191028_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='DSM_V_CODE_1',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='DSM_V_CODE_2',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='DSM_V_CODE_3',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='DSM_V_CODE_4',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='DSM_V_CODE_5',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Diagnosis_1',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Diagnosis_2',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Diagnosis_3',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Diagnosis_4',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Diagnosis_5',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Longterm_Goals_for_Discharge',
        ),
        migrations.RemoveField(
            model_name='initial_treatment_plan',
            name='Problems_of_Patient',
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='DSM_V_CODE',
            field=models.CharField(choices=[('305.00', '305.00'), ('303.90', '303.90'), ('291.81', '291.81'), ('305.20', '305.20'), ('304.30', '304.30'), ('292.0', '292.0'), ('292.89', '292.89'), ('305.60', '305.60'), ('304.20', '304.20'), ('305.50', '305.50'), ('304.00', '304.00'), ('305.30', '305.30'), ('304.60', '304.60'), ('305.40', '305.40'), ('304.10', '304.10')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Diagnosis',
            field=models.CharField(choices=[('Alcohol use disorder,Mild', 'Alcohol use disorder,Mild'), ('Alcohol use disorder,Moderate', 'Alcohol use disorder,Moderate'), ('Alcohol use disorder,Severe', 'Alcohol use disorder,Severe'), ('Alcohol withdrawl', 'Alcohol withdrawl'), ('Cannabis use disorder,Mild', 'Cannabis use disorder,Mild'), ('Cannabis use disorder,Moderate', 'Cannabis use disorder,Moderate'), ('Cannabis use disorder,Severe', 'Cannabis use disorder,Severe'), ('Cannabis withdrawl', 'Cannabis withdrawl'), ('Cannabis-induced anxietu disorder', 'Cannabis-induced anxiety disorder'), ('Cocaine use disorder,Mild', 'Cocaine use disorder,Mild'), ('Cocaine use disorder,Moderate', 'Cocaine use disorder,Moderate'), ('Cocaine use disorder,Severe', 'Cocaine use disorder,Severe'), ('Cocaine withdrawl', 'Cocaine withdrawl'), ('Cocaine-induced anxiety disorder', 'Cocaine-induced anxiety disorder'), ('Opioid use disorder,Mild', 'Opioid use disorder,Mild'), ('Opioid use disorder,Moderate', 'Opioid use disorder,Moderate'), ('Opioid use disorder,Severe', 'Opioid use disorder,Severe'), ('Opioid withdrawl', 'Opioid withdrawl'), ('Opioid withdrawl,delirium', 'Opioid withdrawl,delirium'), ('other hellucinogen use disorder,Mild', 'other hellucinogen use disorder,Mild'), ('other hellucinogen use disorder,Moderate', 'other hellucinogen use disorder,Moderate'), ('other hellucinogen use disorder,Severe', 'other hellucinogen use disorder,Severe'), ('other hellucinogen-induced anxiety disorder', 'other hellucinogen-induced anxiety disorder'), ('Phencyclidine use disorder,Mild', 'Phencyclidine use disorder,Mild'), ('Phencyclidine use disorder,Moderate', 'Phencyclidine use disorder,Moderate'), ('Phencyclidine use disorder,Severe', 'Phencyclidine use disorder,Severe'), ('Phencyclidine-induced anxiety disorder', 'Phencyclidine-induced anxiety disorder'), ('Sedative,hypnotic or anxiolytic use disorder,Mild', 'Sedative,hypnotic or anxiolytic use disorder,Mild'), ('Sedative,hypnotic or anxiolytic use disorder,Mpderate', 'Sedative,hypnotic or anxiolytic use disorder,Moderate'), ('Sedative,hypnotic or anxiolytic use disorder,Severe', 'Sedative,hypnotic or anxiolytic use disorder,Severe'), ('Sedative,hypnotic or anxiolytic withdrawl', 'Sedative,hypnotic or anxiolytic withdrawl')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Longterm_Goals_for_Discharge_1',
            field=models.CharField(choices=[('Maintain A program of recovery,free from impulsive behaviour and addictions', 'Maintain A program of recovery,free from impulsive behaviour and addictions'), ('Reduce the frequency of impuslive behaviour and increase the frequency of behaviour that is carefully thought out', 'Reduce the frequency of impuslive behaviour and increase the frequency of behaviour that is carefully thought out')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Longterm_Goals_for_Discharge_2',
            field=models.CharField(choices=[('Maintain A program of recovery,free of addictions and legal conflicts', 'Maintain A program of recovery,free of addictions and legal conflicts'), ('Accept responsibility for legal problems without blaming others', 'Accept responsibility for legal problems without blaming others'), ('consult with legal authorities(e.g., attorney, probation officer, police, court official) to make plans for adjugating legal conflicts', 'consult with legal authorities(e.g., attorney, probation officer, police, court official) to make plans for adjugating legal conflicts'), ('Understand the need to maintain abstinence to remain free of negative conseqences, which include legal problem', 'Understand the need to maintain abstinence to remain free of negative conseqences, which include legal problem'), ('Decrease antisocial behaviours and increase prosocial behavious', 'Decrease antisocial behaviours and increase prosocial behavious')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Longterm_Goals_for_Discharge_3',
            field=models.CharField(choices=[('Maintain A program of recovery,free of addictions and negative impact of deficient environment', 'Maintain A program of recovery,free of addictions and negative impact of deficient environment'), ('Improve the social, occupational , financial and living situation sufficiently to increase the probability of a successful recovery from addiction', 'Improve the social, occupational , financial and living situation sufficiently to increase the probability of a successful recovery from addiction'), ('Understand the negative impact of current enviroment on addiction recovery', 'Understand the negative impact of current enviroment on addiction recovery'), ('Develop a peer group that is supportive of revovery', 'Develop a peer group that is supportive of revovery'), ('Family members support the client recovery ', 'Family members support the client recovery')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Longterm_Goals_for_Discharge_4',
            field=models.CharField(choices=[('Maintain A program of recovery,free of addictions and negative impact of medical issues', 'Maintain A program of recovery,free of addictions and negative impact of medical issues'), ('Resolve medical problem and return to a normal level of functioning', 'Resolve medical problem and return to a normal level of functioning'), ('Understand the relationship between medical issues', 'Understand the relationship between medical issues')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Problems_of_Patient_1',
            field=models.CharField(choices=[('Exhibits a tendency to act too quickly on imoulses', 'Exhibits a tendency to act too quickly on imoulses'), ('Demonstartes difficulty in patience, particularly while waiting for someone or waiting in line', 'Demonstartes difficulty in patience, particularly while waiting for someone or waiting in line'), ('Impulsively facilitate a self-defeating pattern of addiction behaviour', 'Impulsively facilitate a self-defeating pattern of addiction behaviour'), ('Reports loss of overaggressiveness impulses, resulting in assault , self destructive behaviour, and/or damage to property', 'Reports loss of overaggressiveness impulses, resulting in assault , self destructive behaviour, and/or damage to property'), ('Desires Everything Immediately-demonstrates a deceased ability to delay pleasure or gratification', 'Desires Everything Immediately-demonstrates a deceased ability to delay pleasure or gratification'), ('Has a history of acting out atleast in two areas that are potentially self damaging(e.g., spending money,sexual activity,reckless driving,addiction)', 'Has a history of acting out atleast in two areas that are potentially self damaging(e.g., spending money,sexual activity,reckless driving,addiction'), ('Overreacts to mildly averse or pleasure oriented stimulation', 'Overreacts to mildly averse or pleasure oriented stimulation'), ('Expereince a sense of tension or affective arousal before engaging in the impulsive behaviour (e.g., kleptomania or pyromania)', 'Expereince a sense of tension or affective arousal before engaging in the impulsive behaviour (e.g., kleptomania or pyromania)'), ('Senses pleasure,gratification or release at the time of commiting an antisocial act', 'Senses pleasure,gratification or release at the time of commiting an antisocial act')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Problems_of_Patient_2',
            field=models.CharField(choices=[('Presents with legal charges pending adjudication', 'Presents with legal charges pending adjudication'), ('Has  a history of repeated violations of the law, many occuring under the influence of drugs or alcohol', 'Has  a history of repeated violations of the law, many occuring under the influence of drugs or alcohol'), ('Unresolved legal probolems are complicaiting recovery from addiction', 'Unresolved legal probolems are complicaiting recovery from addiction'), ('Express a fear of legal system adjudicating current problems', 'Express a fear of legal system adjudicating current problems'), ('Has  a history of repeated violations of the law related to buying ,selling or using illegal substances', 'Has  a history of repeated violations of the law related to buying ,selling or using illegal substances'), ('Is undera court order to seek treatment for addiction', 'Is undera court order to seek treatment for addiction'), ('Express feelings of anger,resentment and fear of abandonment associated with impending divorce', 'Express feelings of anger,resentment and fear of abandonment associated with impending divorce'), ('Chemical dependancy has resulted in several arrests', 'Chemical dependancy has resulted in several arrests'), ('Fears loss freedom due to current legal charges', 'Fears loss freedom due to current legal charges')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Problems_of_Patient_3',
            field=models.CharField(choices=[('lives in an environment which is a high risk for relapse', 'lives in an environment which is a high risk for relapse'), ('Lives with an individual who is a regular user/abuser of alochol/drugs', 'Lives with an individual who is a regular user/abuser of alochol/drugs'), ('Experiencing significant social isolation,withdrawl from social life', 'Experiencing significant social isolation,withdrawl from social life'), ('Lives in an environment in which there is high risk of physical ,sexual or emotional abuse', 'Lives in an environment in which there is high risk of physical ,sexual or emotional abuse'), ('Has many friends who are criminals or addicted', 'Has many friends who are criminals or addicted'), ('Reports that family is angry or negative towards the addict and not supportive of recovery program', 'Reports that family is angry or negative towards the addict and not supportive of recovery program'), ('Present as financial destitute and in need of assistance of adequeste food and shelter', 'Present as financial destitute and in need of assistance of adequeste food and shelter'), ('Associates nith peer group members who are regular user/abuser of alcohol/drugs', 'Associates nith peer group members who are regular user/abuser of alcohol/drugs'), ('Lives ina neighbourhood that has high incidence of alcohol and drugs as well as crimes', 'Lives ina neighbourhood that has high incidence of alcohol and drugs as well as crime')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='Problems_of_Patient_4',
            field=models.CharField(choices=[('Has been diagnosed with medical problems that complicate the recovery from addiction', 'Has been diagnosed with medical problems that complicate the recovery from addiction'), ('Presents with medical problems that require medical monitoring of medications or assistance with mobility', 'Presents with medical problems that require medical monitoring of medications or assistance with mobility'), ('Has organic brain syndrome that compromises learning as a result of use of mood altering chemicals', 'Has organic brain syndrome that compromises learning as a result of use of mood altering chemicals'), ('Demonstartes inability to  self-administer prescribed medication', 'Demonstartes inability to  self-administer prescribed medication'), ('Suffers from chronic pain syndrome, which places the client for high risk replace', 'Suffers from chronic pain syndrome, which places the client for high risk relapse'), ('Has mediacl problems that require medical/nursing assistance', 'Has mediacl problems that require medical/nursing assistance'), ('Self-medicates medical problems through use of mood altering chemicals', 'Self-medicates medical problems through use of mood altering chemicals'), ('Reports negative emotions concerning medical illness that led to addiction', 'Reports negative emotions concerning medical illness that led to addiction'), ('Demonstrates a compromised ability to concentrate on recovery due to severity of medical problems', 'Demonstrates a compromised ability to concentrate on recovery due to severity of medical problems'), ('Blames substance abuse on medical issues and denies a primary substance abuse disorder', 'Blames substance abuse on medical issues and denies a primary substance abuse disorder'), ('Doctor shops in order to obtain medication necessary to reduce symptoms', 'Doctor shops in order to obtain medication necessary to reduce symptoms')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='Barriers',
            field=models.CharField(choices=[('Transportation', 'Transportation'), ('Physical Disability', 'Physical Disability'), ('Mental Health', 'Mental Health'), ('Language Problem', 'Language Problem'), ('Religious Restrictions', 'Religious Restrictions'), ('Cultural Restrictions', 'Cultural Restrictions')], max_length=300),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='Strengths',
            field=models.CharField(choices=[('Educated', 'Educated'), ('Intelligent Motivated', 'Intelligent Motivated'), ('family Support', 'family Support'), ('Employed', 'Employed'), ('Hardworking', 'Hardworking'), ('Have Financial Resources', 'Have Financial Resources'), ('Have 12 steps Recovery Support', 'Have 12 steps Recovery Support'), ('Good Health', 'Good Health'), ('Other:', 'Other:')], max_length=300),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='Stressors',
            field=models.CharField(choices=[('Unemployment', 'Unemployment'), ('Homelessness', 'Homelessness'), ('Substance use in Household', 'Substance use in Household'), ('Family Conflict', 'Family Conflict'), ('Relationship Problem', 'Relationship Problem'), ('Financial Problem', 'Financial Problem'), ('Legal Problem', 'Legal Problem'), ('Health Problem', 'Health Problem'), ('Mental Health Problem', 'Mental Health Problem'), ('Education Problem', 'Education Problem'), ('Medical Problem', 'Medical Problem')], max_length=300),
        ),
    ]
