# Generated by Django 2.2.6 on 2019-10-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191028_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='Acute',
            field=models.CharField(choices=[('Client appears to be making little or no progress', 'Client appears to be making little or no progress'), ('Client appears to be making considerable progress', 'Client appears to be making considerable progress'), ('Resolved', 'Resolved'), ('Not Applicable', 'Not Applicable'), ('Not Assessed', 'Not Assessed')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='Biomedical',
            field=models.CharField(choices=[('Client appears to be making little or no progress', 'Client appears to be making little or no progress'), ('Client appears to be making considerable progress', 'Client appears to be making considerable progress'), ('Resolved', 'Resolved'), ('Not Applicable', 'Not Applicable'), ('Not Assessed', 'Not Assessed')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='Emotional_or_Behavioral',
            field=models.CharField(choices=[('Client appears to be making little or no progress', 'Client appears to be making little or no progress'), ('Client appears to be making considerable progress', 'Client appears to be making considerable progress'), ('Resolved', 'Resolved'), ('Not Applicable', 'Not Applicable'), ('Not Assessed', 'Not Assessed')], default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='DX',
            field=models.CharField(choices=[('Alcohol use disorder,Mild', 'Alcohol use disorder,Mild'), ('Alcohol use disorder,Moderate', 'Alcohol use disorder,Moderate'), ('Alcohol use disorder,Severe', 'Alcohol use disorder,Severe'), ('Cannabis use disorder,Mild', 'Cannabis use disorder,Mild'), ('Cannabis use disorder,Moderate', 'Cannabis use disorder,Moderate'), ('Cannabis use disorder,Severe', 'Cannabis use disorder,Severe'), ('Cocaine use disorder,Mild', 'Cocaine use disorder,Mild'), ('Cocaine use disorder,Moderate', 'Cocaine use disorder,Moderate'), ('Cocaine use disorder,Severe', 'Cocaine use disorder,Severe'), ('Opioid use disorder,Mild', 'Opioid use disorder,Mild'), ('Opioid use disorder,Moderate', 'Opioid use disorder,Moderate'), ('In Partial remission', 'In Partial remission'), ('In full remission', 'In full remission'), ('Other:', 'Other:')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='List_Treatment_Plan_Objectives_Discussed',
            field=models.CharField(choices=[('Abstinenece', 'Abstinenece'), ('Employment', 'Employment'), ('Family Conflict', 'Family Conflict'), ('Housing', 'Housing'), ('Mental Health', 'Mental Health'), ('Education', 'Education'), ('Legal', 'Legal'), ('Support Network', 'Support Network')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Mood',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Anxious', 'Anxious'), ('Depressed', 'Depressed'), ('Angry', 'Angry'), ('Euphoric', 'Euphoric'), ('Other:', 'Other:')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Relapse_Potential',
            field=models.CharField(choices=[('Client appears to be making little or no progress', 'Client appears to be making little or no progress'), ('Client appears to be making considerable progress', 'Client appears to be making considerable progress'), ('Resolved', 'Resolved'), ('Not Applicable', 'Not Applicable'), ('Not Assessed', 'Not Assessed')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Resistance',
            field=models.CharField(choices=[('Client appears to be making little or no progress', 'Client appears to be making little or no progress'), ('Client appears to be making considerable progress', 'Client appears to be making considerable progress'), ('Resolved', 'Resolved'), ('Not Applicable', 'Not Applicable'), ('Not Assessed', 'Not Assessed')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Session_Type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Group', 'Group'), ('Case Note', 'Case Note')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Thought_Process',
            field=models.CharField(choices=[('Coherent', 'Coherent'), ('Logical', 'Logical'), ('Tangential', 'Tangential'), ('Loose', 'Loose'), ('Circumstantial', 'Circumstantial'), ('Fight of ideas', 'Fight of ideas')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Topic_of_Discussion',
            field=models.CharField(choices=[('Relationships', 'Relationships'), ('Work Problems', 'Work Problems'), ('Alcohol/Drug Problems', 'Alcohol/Drug Problems'), ('Parenting', 'Parenting'), ('Abuse', 'Abuse'), ('Childhood/Family of origin', 'Childhood/Family of origin'), ('Sexual', 'Sexual'), ('Homework assignments', 'Homework assignments'), ('Process', 'Process'), ('Logistics/Structure', 'Logistics/Structure'), ('HIV/AIDS', 'HIV/AIDS'), ('Other:', 'Other:')], max_length=300),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='Type_of_group',
            field=models.CharField(choices=[('Process Group', 'Process Group'), ('Education Group', 'Education Group'), ('Family', 'Family'), ('N/A', 'N/A')], max_length=300),
        ),
    ]
