# Generated by Django 2.2.6 on 2019-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191028_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='other',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('OP', 'OP'), ('IOP', 'IOP'), ('other', 'other')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('OP', 'OP'), ('IOP', 'IOP'), ('other', 'other')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='others',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('OP', 'OP'), ('IOP', 'IOP'), ('other', 'other')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='others',
            field=models.CharField(choices=[('Inpatient', 'Inpatient'), ('OP', 'OP'), ('IOP', 'IOP'), ('other', 'other')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
