# Generated by Django 2.2.6 on 2019-10-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191028_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_progress_note',
            name='others',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='others',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
