# Generated by Django 2.2.6 on 2019-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20191028_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hrrs_intake_screen',
            old_name='other',
            new_name='other_referral',
        ),
        migrations.RenameField(
            model_name='hrrs_progress_note',
            old_name='other',
            new_name='other_DX',
        ),
        migrations.RenameField(
            model_name='hrrs_progress_note',
            old_name='others',
            new_name='other_mood',
        ),
        migrations.RenameField(
            model_name='initial_treatment_plan',
            old_name='others',
            new_name='other_strength',
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
