# Generated by Django 2.2.6 on 2019-10-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20191028_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_acute',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_biomedical',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_emotional',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_relapse_potential',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_resistance',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_session',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hrrs_progress_note',
            name='other_thought',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
