# Generated by Django 2.2.6 on 2019-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20191029_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_1',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_2',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_3',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_4',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_5',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_6',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_discharge_planning',
            name='other_Option_7',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='other_Option_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='other_Option_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='other_Option_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrrs_intake_screen',
            name='other_Option_4',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Barriers',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_DSM_V_CODE',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Diagnosis',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Stressors',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_10',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_11',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_12',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_13',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_14',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_15',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_2',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_3',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_4',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_5',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_6',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_7',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_8',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_Option_9',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sogs',
            name='other_played_cards_for_money',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
