# Generated by Django 2.2.6 on 2019-10-30 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20191031_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='other_Option_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='other_Option_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='other_Option_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='other_Option_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='recommended_program',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='other_Barriers',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='other_DSM_V_CODE',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='other_Diagnosis',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='initial_treatment_plan',
            name='other_Stressors',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_Option_9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sogs',
            name='other_played_cards_for_money',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
