# Generated by Django 2.2.6 on 2019-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20191031_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='initial_treatment_plan',
            name='other_Option_8',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
