# Generated by Django 2.2.6 on 2019-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20191104_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='Intake_Appointment',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='Rescheduled',
            field=models.DateField(blank=True),
        ),
    ]
