# Generated by Django 2.2.6 on 2019-11-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20191105_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='DOB',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='Date1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='Intake_Appointment',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='Rescheduled',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='date',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hrrs_intake_screen',
            name='date_last_used',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
