# Generated by Django 2.2.6 on 2019-11-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20191105_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartreviewtool',
            name='clientName',
            field=models.CharField(db_column='Client Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='demographicmodel',
            name='name_page_1',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
    ]
